// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: addresses_contacts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (
    id,
    tenant_id,
    type,
    label,
    line1,
    line2,
    city,
    state,
    postal_code,
    country_code,
    latitude,
    longitude,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, tenant_id, type, label, line1, line2, city, state, postal_code, country_code, latitude, longitude, created_at, updated_at
`

type CreateAddressParams struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Type        string             `json:"type"`
	Label       *string            `json:"label"`
	Line1       string             `json:"line1"`
	Line2       *string            `json:"line2"`
	City        string             `json:"city"`
	State       *string            `json:"state"`
	PostalCode  *string            `json:"postal_code"`
	CountryCode string             `json:"country_code"`
	Latitude    pgtype.Numeric     `json:"latitude"`
	Longitude   pgtype.Numeric     `json:"longitude"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.ID,
		arg.TenantID,
		arg.Type,
		arg.Label,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.CountryCode,
		arg.Latitude,
		arg.Longitude,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Label,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
    id,
    tenant_id,
    party_id,
    organization_id,
    type,
    value,
    label,
    is_primary,
    verified_at,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, party_id, organization_id, type, value, label, is_primary, verified_at, created_at, updated_at
`

type CreateContactParams struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	PartyID        pgtype.UUID        `json:"party_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Type           string             `json:"type"`
	Value          string             `json:"value"`
	Label          *string            `json:"label"`
	IsPrimary      bool               `json:"is_primary"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.ID,
		arg.TenantID,
		arg.PartyID,
		arg.OrganizationID,
		arg.Type,
		arg.Value,
		arg.Label,
		arg.IsPrimary,
		arg.VerifiedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PartyID,
		&i.OrganizationID,
		&i.Type,
		&i.Value,
		&i.Label,
		&i.IsPrimary,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts
WHERE tenant_id = $1 AND id = $2
`

type DeleteContactParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.Exec(ctx, deleteContact, arg.TenantID, arg.ID)
	return err
}

const getAddressByID = `-- name: GetAddressByID :one
SELECT id, tenant_id, type, label, line1, line2, city, state, postal_code, country_code, latitude, longitude, created_at, updated_at FROM addresses
WHERE tenant_id = $1 AND id = $2 LIMIT 1
`

type GetAddressByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetAddressByID(ctx context.Context, arg GetAddressByIDParams) (Address, error) {
	row := q.db.QueryRow(ctx, getAddressByID, arg.TenantID, arg.ID)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Label,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.State,
		&i.PostalCode,
		&i.CountryCode,
		&i.Latitude,
		&i.Longitude,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkOrganizationAddress = `-- name: LinkOrganizationAddress :exec
INSERT INTO organization_addresses (
    tenant_id, organization_id, address_id, address_type, is_primary, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) ON CONFLICT (organization_id, address_id, address_type) DO UPDATE
SET is_primary = EXCLUDED.is_primary
`

type LinkOrganizationAddressParams struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AddressID      pgtype.UUID        `json:"address_id"`
	AddressType    string             `json:"address_type"`
	IsPrimary      bool               `json:"is_primary"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LinkOrganizationAddress(ctx context.Context, arg LinkOrganizationAddressParams) error {
	_, err := q.db.Exec(ctx, linkOrganizationAddress,
		arg.TenantID,
		arg.OrganizationID,
		arg.AddressID,
		arg.AddressType,
		arg.IsPrimary,
		arg.CreatedAt,
	)
	return err
}

const linkPartyAddress = `-- name: LinkPartyAddress :exec
INSERT INTO party_addresses (
    tenant_id, party_id, address_id, address_type, is_primary, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) ON CONFLICT (party_id, address_id, address_type) DO UPDATE
SET is_primary = EXCLUDED.is_primary
`

type LinkPartyAddressParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PartyID     pgtype.UUID        `json:"party_id"`
	AddressID   pgtype.UUID        `json:"address_id"`
	AddressType string             `json:"address_type"`
	IsPrimary   bool               `json:"is_primary"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LinkPartyAddress(ctx context.Context, arg LinkPartyAddressParams) error {
	_, err := q.db.Exec(ctx, linkPartyAddress,
		arg.TenantID,
		arg.PartyID,
		arg.AddressID,
		arg.AddressType,
		arg.IsPrimary,
		arg.CreatedAt,
	)
	return err
}

const listOrganizationAddresses = `-- name: ListOrganizationAddresses :many
SELECT a.id, a.tenant_id, a.type, a.label, a.line1, a.line2, a.city, a.state, a.postal_code, a.country_code, a.latitude, a.longitude, a.created_at, a.updated_at, oa.is_primary, oa.address_type as link_type
FROM addresses a
JOIN organization_addresses oa ON oa.address_id = a.id AND oa.tenant_id = a.tenant_id
WHERE a.tenant_id = $1 AND oa.organization_id = $2
ORDER BY oa.is_primary DESC, a.created_at DESC
`

type ListOrganizationAddressesParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListOrganizationAddressesRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Type        string             `json:"type"`
	Label       *string            `json:"label"`
	Line1       string             `json:"line1"`
	Line2       *string            `json:"line2"`
	City        string             `json:"city"`
	State       *string            `json:"state"`
	PostalCode  *string            `json:"postal_code"`
	CountryCode string             `json:"country_code"`
	Latitude    pgtype.Numeric     `json:"latitude"`
	Longitude   pgtype.Numeric     `json:"longitude"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsPrimary   bool               `json:"is_primary"`
	LinkType    string             `json:"link_type"`
}

func (q *Queries) ListOrganizationAddresses(ctx context.Context, arg ListOrganizationAddressesParams) ([]ListOrganizationAddressesRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationAddresses, arg.TenantID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationAddressesRow{}
	for rows.Next() {
		var i ListOrganizationAddressesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Label,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPrimary,
			&i.LinkType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationContacts = `-- name: ListOrganizationContacts :many
SELECT id, tenant_id, party_id, organization_id, type, value, label, is_primary, verified_at, created_at, updated_at FROM contacts
WHERE tenant_id = $1 AND organization_id = $2
ORDER BY is_primary DESC, created_at ASC
`

type ListOrganizationContactsParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListOrganizationContacts(ctx context.Context, arg ListOrganizationContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listOrganizationContacts, arg.TenantID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PartyID,
			&i.OrganizationID,
			&i.Type,
			&i.Value,
			&i.Label,
			&i.IsPrimary,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartyAddresses = `-- name: ListPartyAddresses :many
SELECT a.id, a.tenant_id, a.type, a.label, a.line1, a.line2, a.city, a.state, a.postal_code, a.country_code, a.latitude, a.longitude, a.created_at, a.updated_at, pa.is_primary, pa.address_type as link_type
FROM addresses a
JOIN party_addresses pa ON pa.address_id = a.id AND pa.tenant_id = a.tenant_id
WHERE a.tenant_id = $1 AND pa.party_id = $2
ORDER BY pa.is_primary DESC, a.created_at DESC
`

type ListPartyAddressesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PartyID  pgtype.UUID `json:"party_id"`
}

type ListPartyAddressesRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Type        string             `json:"type"`
	Label       *string            `json:"label"`
	Line1       string             `json:"line1"`
	Line2       *string            `json:"line2"`
	City        string             `json:"city"`
	State       *string            `json:"state"`
	PostalCode  *string            `json:"postal_code"`
	CountryCode string             `json:"country_code"`
	Latitude    pgtype.Numeric     `json:"latitude"`
	Longitude   pgtype.Numeric     `json:"longitude"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsPrimary   bool               `json:"is_primary"`
	LinkType    string             `json:"link_type"`
}

func (q *Queries) ListPartyAddresses(ctx context.Context, arg ListPartyAddressesParams) ([]ListPartyAddressesRow, error) {
	rows, err := q.db.Query(ctx, listPartyAddresses, arg.TenantID, arg.PartyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPartyAddressesRow{}
	for rows.Next() {
		var i ListPartyAddressesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Label,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.State,
			&i.PostalCode,
			&i.CountryCode,
			&i.Latitude,
			&i.Longitude,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsPrimary,
			&i.LinkType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartyContacts = `-- name: ListPartyContacts :many
SELECT id, tenant_id, party_id, organization_id, type, value, label, is_primary, verified_at, created_at, updated_at FROM contacts
WHERE tenant_id = $1 AND party_id = $2
ORDER BY is_primary DESC, created_at ASC
`

type ListPartyContactsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PartyID  pgtype.UUID `json:"party_id"`
}

func (q *Queries) ListPartyContacts(ctx context.Context, arg ListPartyContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listPartyContacts, arg.TenantID, arg.PartyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PartyID,
			&i.OrganizationID,
			&i.Type,
			&i.Value,
			&i.Label,
			&i.IsPrimary,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
