// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs
WHERE tenant_id = $1
  AND ($2::text IS NULL OR entity_type = $2)
  AND ($3::uuid IS NULL OR entity_id = $3)
  AND ($4::uuid IS NULL OR actor_id = $4)
  AND ($5::text IS NULL OR action = $5)
`

type CountAuditLogsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType *string     `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	Action     *string     `json:"action"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.ActorID,
		arg.Action,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    id, tenant_id, actor_id, actor_type, action, entity_type, entity_id, changes, metadata, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, tenant_id, actor_id, actor_type, action, entity_type, entity_id, changes, metadata, created_at
`

type CreateAuditLogParams struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	ActorType  string             `json:"actor_type"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Changes    []byte             `json:"changes"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.ActorType,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorID,
		&i.ActorType,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Changes,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT 
    id, tenant_id, actor_id, actor_type, action, entity_type, entity_id, changes, metadata, created_at
FROM audit_logs
WHERE tenant_id = $1
  AND ($4::text IS NULL OR entity_type = $4)
  AND ($5::uuid IS NULL OR entity_id = $5)
  AND ($6::uuid IS NULL OR actor_id = $6)
  AND ($7::text IS NULL OR action = $7)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	EntityType *string     `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	Action     *string     `json:"action"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.EntityType,
		arg.EntityID,
		arg.ActorID,
		arg.Action,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorID,
			&i.ActorType,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
