// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: communication.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications
WHERE tenant_id = $1 AND user_id = $2 AND is_read = false
`

type CountUnreadNotificationsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.TenantID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
    id, tenant_id, entity_type, entity_id, author_id, type,
    content, mentions, parent_id, is_pinned, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, entity_type, entity_id, author_id, type, content, mentions, parent_id, is_pinned, metadata, created_at, updated_at
`

type CreateCommentParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	AuthorID   pgtype.UUID `json:"author_id"`
	Type       string      `json:"type"`
	Content    string      `json:"content"`
	Mentions   []byte      `json:"mentions"`
	ParentID   pgtype.UUID `json:"parent_id"`
	IsPinned   bool        `json:"is_pinned"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.AuthorID,
		arg.Type,
		arg.Content,
		arg.Mentions,
		arg.ParentID,
		arg.IsPinned,
		arg.Metadata,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.EntityID,
		&i.AuthorID,
		&i.Type,
		&i.Content,
		&i.Mentions,
		&i.ParentID,
		&i.IsPinned,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    id, tenant_id, user_id, actor_id, type, title, message,
    entity_type, entity_id, is_read, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, user_id, actor_id, type, title, message, entity_type, entity_id, is_read, read_at, metadata, created_at
`

type CreateNotificationParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	UserID     pgtype.UUID `json:"user_id"`
	ActorID    pgtype.UUID `json:"actor_id"`
	Type       string      `json:"type"`
	Title      string      `json:"title"`
	Message    string      `json:"message"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	IsRead     bool        `json:"is_read"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.ActorID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.EntityType,
		arg.EntityID,
		arg.IsRead,
		arg.Metadata,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ActorID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.EntityType,
		&i.EntityID,
		&i.IsRead,
		&i.ReadAt,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE tenant_id = $1 AND id = $2
`

type DeleteCommentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteComment(ctx context.Context, arg DeleteCommentParams) error {
	_, err := q.db.Exec(ctx, deleteComment, arg.TenantID, arg.ID)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT id, tenant_id, entity_type, entity_id, author_id, type, content, mentions, parent_id, is_pinned, metadata, created_at, updated_at FROM comments
WHERE tenant_id = $1 AND id = $2
`

type GetCommentByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetCommentByID(ctx context.Context, arg GetCommentByIDParams) (Comment, error) {
	row := q.db.QueryRow(ctx, getCommentByID, arg.TenantID, arg.ID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.EntityID,
		&i.AuthorID,
		&i.Type,
		&i.Content,
		&i.Mentions,
		&i.ParentID,
		&i.IsPinned,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, tenant_id, user_id, actor_id, type, title, message, entity_type, entity_id, is_read, read_at, metadata, created_at FROM notifications
WHERE tenant_id = $1 AND id = $2
`

type GetNotificationByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, arg.TenantID, arg.ID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ActorID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.EntityType,
		&i.EntityID,
		&i.IsRead,
		&i.ReadAt,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listCommentsByEntity = `-- name: ListCommentsByEntity :many
SELECT 
    c.id,
    c.tenant_id,
    c.entity_type,
    c.entity_id,
    c.author_id,
    c.type,
    c.content,
    c.mentions,
    c.parent_id,
    c.is_pinned,
    c.metadata,
    c.created_at,
    c.updated_at,
    u.name AS author_name,
    u.email AS author_email
FROM comments c
JOIN users u ON c.author_id = u.id
WHERE c.tenant_id = $1 AND c.entity_type = $2 AND c.entity_id = $3
ORDER BY c.is_pinned DESC, c.created_at ASC
`

type ListCommentsByEntityParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

type ListCommentsByEntityRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	AuthorID    pgtype.UUID        `json:"author_id"`
	Type        string             `json:"type"`
	Content     string             `json:"content"`
	Mentions    []byte             `json:"mentions"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	IsPinned    bool               `json:"is_pinned"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	AuthorName  string             `json:"author_name"`
	AuthorEmail string             `json:"author_email"`
}

func (q *Queries) ListCommentsByEntity(ctx context.Context, arg ListCommentsByEntityParams) ([]ListCommentsByEntityRow, error) {
	rows, err := q.db.Query(ctx, listCommentsByEntity, arg.TenantID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommentsByEntityRow{}
	for rows.Next() {
		var i ListCommentsByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityType,
			&i.EntityID,
			&i.AuthorID,
			&i.Type,
			&i.Content,
			&i.Mentions,
			&i.ParentID,
			&i.IsPinned,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorName,
			&i.AuthorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, tenant_id, user_id, actor_id, type, title, message, entity_type, entity_id, is_read, read_at, metadata, created_at FROM notifications
WHERE tenant_id = $1 AND user_id = $2
  AND (CASE WHEN $3::boolean THEN is_read = false ELSE true END)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListNotificationsByUserParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Column3  bool        `json:"column_3"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser,
		arg.TenantID,
		arg.UserID,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ActorID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.EntityType,
			&i.EntityID,
			&i.IsRead,
			&i.ReadAt,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET is_read = true, read_at = NOW()
WHERE tenant_id = $1 AND user_id = $2 AND is_read = false
`

type MarkAllNotificationsReadParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, arg.TenantID, arg.UserID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications
SET is_read = true, read_at = NOW()
WHERE tenant_id = $1 AND user_id = $2 AND id = $3
`

type MarkNotificationReadParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.TenantID, arg.UserID, arg.ID)
	return err
}
