// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_fields.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomFieldDefinition = `-- name: CreateCustomFieldDefinition :one
INSERT INTO custom_field_definitions (
    id, tenant_id, entity_type, code, name, description,
    data_type, options, is_required, default_value, validation_rules,
    sort_order, is_active, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15
) RETURNING id, tenant_id, entity_type, code, name, description, data_type, options, is_required, default_value, validation_rules, sort_order, is_active, created_at, updated_at
`

type CreateCustomFieldDefinitionParams struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	EntityType      string             `json:"entity_type"`
	Code            string             `json:"code"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	DataType        string             `json:"data_type"`
	Options         []byte             `json:"options"`
	IsRequired      bool               `json:"is_required"`
	DefaultValue    []byte             `json:"default_value"`
	ValidationRules []byte             `json:"validation_rules"`
	SortOrder       int32              `json:"sort_order"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCustomFieldDefinition(ctx context.Context, arg CreateCustomFieldDefinitionParams) (CustomFieldDefinition, error) {
	row := q.db.QueryRow(ctx, createCustomFieldDefinition,
		arg.ID,
		arg.TenantID,
		arg.EntityType,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.DataType,
		arg.Options,
		arg.IsRequired,
		arg.DefaultValue,
		arg.ValidationRules,
		arg.SortOrder,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CustomFieldDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DataType,
		&i.Options,
		&i.IsRequired,
		&i.DefaultValue,
		&i.ValidationRules,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomFieldDefinition = `-- name: DeleteCustomFieldDefinition :exec
DELETE FROM custom_field_definitions
WHERE tenant_id = $1 AND id = $2
`

type DeleteCustomFieldDefinitionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteCustomFieldDefinition(ctx context.Context, arg DeleteCustomFieldDefinitionParams) error {
	_, err := q.db.Exec(ctx, deleteCustomFieldDefinition, arg.TenantID, arg.ID)
	return err
}

const deleteEntityCustomFields = `-- name: DeleteEntityCustomFields :exec
DELETE FROM entity_custom_fields
WHERE tenant_id = $1 AND entity_type = $2 AND entity_id = $3
`

type DeleteEntityCustomFieldsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) DeleteEntityCustomFields(ctx context.Context, arg DeleteEntityCustomFieldsParams) error {
	_, err := q.db.Exec(ctx, deleteEntityCustomFields, arg.TenantID, arg.EntityType, arg.EntityID)
	return err
}

const findEntitiesByCustomFieldMatch = `-- name: FindEntitiesByCustomFieldMatch :many
SELECT entity_id, values FROM entity_custom_fields
WHERE tenant_id = $1 AND entity_type = $2 AND values @> $3::jsonb
`

type FindEntitiesByCustomFieldMatchParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	EntityType  string      `json:"entity_type"`
	MatchValues []byte      `json:"match_values"`
}

type FindEntitiesByCustomFieldMatchRow struct {
	EntityID pgtype.UUID `json:"entity_id"`
	Values   []byte      `json:"values"`
}

func (q *Queries) FindEntitiesByCustomFieldMatch(ctx context.Context, arg FindEntitiesByCustomFieldMatchParams) ([]FindEntitiesByCustomFieldMatchRow, error) {
	rows, err := q.db.Query(ctx, findEntitiesByCustomFieldMatch, arg.TenantID, arg.EntityType, arg.MatchValues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindEntitiesByCustomFieldMatchRow{}
	for rows.Next() {
		var i FindEntitiesByCustomFieldMatchRow
		if err := rows.Scan(&i.EntityID, &i.Values); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomFieldDefinitionByCode = `-- name: GetCustomFieldDefinitionByCode :one
SELECT id, tenant_id, entity_type, code, name, description, data_type, options, is_required, default_value, validation_rules, sort_order, is_active, created_at, updated_at FROM custom_field_definitions
WHERE tenant_id = $1 AND entity_type = $2 AND code = $3
`

type GetCustomFieldDefinitionByCodeParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
	Code       string      `json:"code"`
}

func (q *Queries) GetCustomFieldDefinitionByCode(ctx context.Context, arg GetCustomFieldDefinitionByCodeParams) (CustomFieldDefinition, error) {
	row := q.db.QueryRow(ctx, getCustomFieldDefinitionByCode, arg.TenantID, arg.EntityType, arg.Code)
	var i CustomFieldDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DataType,
		&i.Options,
		&i.IsRequired,
		&i.DefaultValue,
		&i.ValidationRules,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomFieldDefinitionByID = `-- name: GetCustomFieldDefinitionByID :one
SELECT id, tenant_id, entity_type, code, name, description, data_type, options, is_required, default_value, validation_rules, sort_order, is_active, created_at, updated_at FROM custom_field_definitions
WHERE tenant_id = $1 AND id = $2
`

type GetCustomFieldDefinitionByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetCustomFieldDefinitionByID(ctx context.Context, arg GetCustomFieldDefinitionByIDParams) (CustomFieldDefinition, error) {
	row := q.db.QueryRow(ctx, getCustomFieldDefinitionByID, arg.TenantID, arg.ID)
	var i CustomFieldDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DataType,
		&i.Options,
		&i.IsRequired,
		&i.DefaultValue,
		&i.ValidationRules,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntityCustomFields = `-- name: GetEntityCustomFields :one
SELECT id, tenant_id, entity_type, entity_id, values, created_at, updated_at FROM entity_custom_fields
WHERE tenant_id = $1 AND entity_type = $2 AND entity_id = $3
`

type GetEntityCustomFieldsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) GetEntityCustomFields(ctx context.Context, arg GetEntityCustomFieldsParams) (EntityCustomField, error) {
	row := q.db.QueryRow(ctx, getEntityCustomFields, arg.TenantID, arg.EntityType, arg.EntityID)
	var i EntityCustomField
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.EntityID,
		&i.Values,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveCustomFieldDefinitions = `-- name: ListActiveCustomFieldDefinitions :many
SELECT id, tenant_id, entity_type, code, name, description, data_type, options, is_required, default_value, validation_rules, sort_order, is_active, created_at, updated_at FROM custom_field_definitions
WHERE tenant_id = $1 AND entity_type = $2 AND is_active = true
ORDER BY sort_order ASC, code ASC
`

type ListActiveCustomFieldDefinitionsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
}

func (q *Queries) ListActiveCustomFieldDefinitions(ctx context.Context, arg ListActiveCustomFieldDefinitionsParams) ([]CustomFieldDefinition, error) {
	rows, err := q.db.Query(ctx, listActiveCustomFieldDefinitions, arg.TenantID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomFieldDefinition{}
	for rows.Next() {
		var i CustomFieldDefinition
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityType,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.DataType,
			&i.Options,
			&i.IsRequired,
			&i.DefaultValue,
			&i.ValidationRules,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomFieldDefinitions = `-- name: ListCustomFieldDefinitions :many
SELECT id, tenant_id, entity_type, code, name, description, data_type, options, is_required, default_value, validation_rules, sort_order, is_active, created_at, updated_at FROM custom_field_definitions
WHERE tenant_id = $1 AND entity_type = $2
ORDER BY sort_order ASC, code ASC
`

type ListCustomFieldDefinitionsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
}

func (q *Queries) ListCustomFieldDefinitions(ctx context.Context, arg ListCustomFieldDefinitionsParams) ([]CustomFieldDefinition, error) {
	rows, err := q.db.Query(ctx, listCustomFieldDefinitions, arg.TenantID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomFieldDefinition{}
	for rows.Next() {
		var i CustomFieldDefinition
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityType,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.DataType,
			&i.Options,
			&i.IsRequired,
			&i.DefaultValue,
			&i.ValidationRules,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomFieldDefinition = `-- name: UpdateCustomFieldDefinition :one
UPDATE custom_field_definitions
SET name = $3,
    description = $4,
    options = $5,
    is_required = $6,
    default_value = $7,
    validation_rules = $8,
    sort_order = $9,
    is_active = $10,
    updated_at = $11
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, entity_type, code, name, description, data_type, options, is_required, default_value, validation_rules, sort_order, is_active, created_at, updated_at
`

type UpdateCustomFieldDefinitionParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Description     *string            `json:"description"`
	Options         []byte             `json:"options"`
	IsRequired      bool               `json:"is_required"`
	DefaultValue    []byte             `json:"default_value"`
	ValidationRules []byte             `json:"validation_rules"`
	SortOrder       int32              `json:"sort_order"`
	IsActive        bool               `json:"is_active"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCustomFieldDefinition(ctx context.Context, arg UpdateCustomFieldDefinitionParams) (CustomFieldDefinition, error) {
	row := q.db.QueryRow(ctx, updateCustomFieldDefinition,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Options,
		arg.IsRequired,
		arg.DefaultValue,
		arg.ValidationRules,
		arg.SortOrder,
		arg.IsActive,
		arg.UpdatedAt,
	)
	var i CustomFieldDefinition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.DataType,
		&i.Options,
		&i.IsRequired,
		&i.DefaultValue,
		&i.ValidationRules,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertEntityCustomFields = `-- name: UpsertEntityCustomFields :one
INSERT INTO entity_custom_fields (
    id, tenant_id, entity_type, entity_id, values, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (tenant_id, entity_type, entity_id)
DO UPDATE SET
    values = EXCLUDED.values,
    updated_at = EXCLUDED.updated_at
RETURNING id, tenant_id, entity_type, entity_id, values, created_at, updated_at
`

type UpsertEntityCustomFieldsParams struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Values     []byte             `json:"values"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertEntityCustomFields(ctx context.Context, arg UpsertEntityCustomFieldsParams) (EntityCustomField, error) {
	row := q.db.QueryRow(ctx, upsertEntityCustomFields,
		arg.ID,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.Values,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EntityCustomField
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.EntityID,
		&i.Values,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
