// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocuments = `-- name: CountDocuments :one
SELECT COUNT(*) FROM documents
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR organization_id = $2)
  AND ($3::varchar IS NULL OR document_type = $3)
  AND ($4::varchar IS NULL OR status = $4)
`

type CountDocumentsParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	DocumentType   *string     `json:"document_type"`
	Status         *string     `json:"status"`
}

func (q *Queries) CountDocuments(ctx context.Context, arg CountDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments,
		arg.TenantID,
		arg.OrganizationID,
		arg.DocumentType,
		arg.Status,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    id,
    tenant_id,
    organization_id,
    document_type,
    document_number,
    document_date,
    party_id,
    status,
    total_amount,
    currency,
    notes,
    metadata,
    created_by,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, tenant_id, organization_id, document_type, document_number, document_date, party_id, status, total_amount, currency, notes, metadata, created_by, created_at, updated_at
`

type CreateDocumentParams struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	DocumentType   string             `json:"document_type"`
	DocumentNumber string             `json:"document_number"`
	DocumentDate   pgtype.Date        `json:"document_date"`
	PartyID        pgtype.UUID        `json:"party_id"`
	Status         string             `json:"status"`
	TotalAmount    int64              `json:"total_amount"`
	Currency       string             `json:"currency"`
	Notes          *string            `json:"notes"`
	Metadata       []byte             `json:"metadata"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.TenantID,
		arg.OrganizationID,
		arg.DocumentType,
		arg.DocumentNumber,
		arg.DocumentDate,
		arg.PartyID,
		arg.Status,
		arg.TotalAmount,
		arg.Currency,
		arg.Notes,
		arg.Metadata,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.DocumentDate,
		&i.PartyID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.Notes,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentLine = `-- name: CreateDocumentLine :one
INSERT INTO document_lines (
    id,
    tenant_id,
    document_id,
    line_number,
    product_id,
    description,
    quantity,
    unit_id,
    unit_price,
    subtotal,
    metadata,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, tenant_id, document_id, line_number, product_id, description, quantity, unit_id, unit_price, subtotal, metadata, created_at, updated_at
`

type CreateDocumentLineParams struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	DocumentID  pgtype.UUID        `json:"document_id"`
	LineNumber  int32              `json:"line_number"`
	ProductID   pgtype.UUID        `json:"product_id"`
	Description string             `json:"description"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	UnitID      pgtype.UUID        `json:"unit_id"`
	UnitPrice   int64              `json:"unit_price"`
	Subtotal    int64              `json:"subtotal"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDocumentLine(ctx context.Context, arg CreateDocumentLineParams) (DocumentLine, error) {
	row := q.db.QueryRow(ctx, createDocumentLine,
		arg.ID,
		arg.TenantID,
		arg.DocumentID,
		arg.LineNumber,
		arg.ProductID,
		arg.Description,
		arg.Quantity,
		arg.UnitID,
		arg.UnitPrice,
		arg.Subtotal,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i DocumentLine
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocumentID,
		&i.LineNumber,
		&i.ProductID,
		&i.Description,
		&i.Quantity,
		&i.UnitID,
		&i.UnitPrice,
		&i.Subtotal,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentTransition = `-- name: CreateDocumentTransition :one
INSERT INTO document_transitions (
    id,
    tenant_id,
    document_id,
    from_status,
    to_status,
    reason,
    actor_id,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, document_id, from_status, to_status, reason, actor_id, created_at
`

type CreateDocumentTransitionParams struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	DocumentID pgtype.UUID        `json:"document_id"`
	FromStatus string             `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Reason     *string            `json:"reason"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDocumentTransition(ctx context.Context, arg CreateDocumentTransitionParams) (DocumentTransition, error) {
	row := q.db.QueryRow(ctx, createDocumentTransition,
		arg.ID,
		arg.TenantID,
		arg.DocumentID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Reason,
		arg.ActorID,
		arg.CreatedAt,
	)
	var i DocumentTransition
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DocumentID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Reason,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocumentLines = `-- name: DeleteDocumentLines :exec
DELETE FROM document_lines
WHERE tenant_id = $1 AND document_id = $2
`

type DeleteDocumentLinesParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DocumentID pgtype.UUID `json:"document_id"`
}

func (q *Queries) DeleteDocumentLines(ctx context.Context, arg DeleteDocumentLinesParams) error {
	_, err := q.db.Exec(ctx, deleteDocumentLines, arg.TenantID, arg.DocumentID)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT d.id, d.tenant_id, d.organization_id, d.document_type, d.document_number, d.document_date, d.party_id, d.status, d.total_amount, d.currency, d.notes, d.metadata, d.created_by, d.created_at, d.updated_at, o.name as organization_name, p.name as party_name
FROM documents d
JOIN organizations o ON o.id = d.organization_id
LEFT JOIN parties p ON p.id = d.party_id
WHERE d.tenant_id = $1 AND d.id = $2 LIMIT 1
`

type GetDocumentByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetDocumentByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	DocumentType     string             `json:"document_type"`
	DocumentNumber   string             `json:"document_number"`
	DocumentDate     pgtype.Date        `json:"document_date"`
	PartyID          pgtype.UUID        `json:"party_id"`
	Status           string             `json:"status"`
	TotalAmount      int64              `json:"total_amount"`
	Currency         string             `json:"currency"`
	Notes            *string            `json:"notes"`
	Metadata         []byte             `json:"metadata"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OrganizationName string             `json:"organization_name"`
	PartyName        *string            `json:"party_name"`
}

func (q *Queries) GetDocumentByID(ctx context.Context, arg GetDocumentByIDParams) (GetDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, arg.TenantID, arg.ID)
	var i GetDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.DocumentDate,
		&i.PartyID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.Notes,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationName,
		&i.PartyName,
	)
	return i, err
}

const getDocumentByNumber = `-- name: GetDocumentByNumber :one
SELECT d.id, d.tenant_id, d.organization_id, d.document_type, d.document_number, d.document_date, d.party_id, d.status, d.total_amount, d.currency, d.notes, d.metadata, d.created_by, d.created_at, d.updated_at, o.name as organization_name, p.name as party_name
FROM documents d
JOIN organizations o ON o.id = d.organization_id
LEFT JOIN parties p ON p.id = d.party_id
WHERE d.tenant_id = $1 AND d.document_type = $2 AND d.document_number = $3 LIMIT 1
`

type GetDocumentByNumberParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	DocumentType   string      `json:"document_type"`
	DocumentNumber string      `json:"document_number"`
}

type GetDocumentByNumberRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	DocumentType     string             `json:"document_type"`
	DocumentNumber   string             `json:"document_number"`
	DocumentDate     pgtype.Date        `json:"document_date"`
	PartyID          pgtype.UUID        `json:"party_id"`
	Status           string             `json:"status"`
	TotalAmount      int64              `json:"total_amount"`
	Currency         string             `json:"currency"`
	Notes            *string            `json:"notes"`
	Metadata         []byte             `json:"metadata"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OrganizationName string             `json:"organization_name"`
	PartyName        *string            `json:"party_name"`
}

func (q *Queries) GetDocumentByNumber(ctx context.Context, arg GetDocumentByNumberParams) (GetDocumentByNumberRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByNumber, arg.TenantID, arg.DocumentType, arg.DocumentNumber)
	var i GetDocumentByNumberRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.DocumentDate,
		&i.PartyID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.Notes,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationName,
		&i.PartyName,
	)
	return i, err
}

const listDocumentLines = `-- name: ListDocumentLines :many
SELECT dl.id, dl.tenant_id, dl.document_id, dl.line_number, dl.product_id, dl.description, dl.quantity, dl.unit_id, dl.unit_price, dl.subtotal, dl.metadata, dl.created_at, dl.updated_at, u.code as unit_code, u.symbol as unit_symbol, p.name as product_name
FROM document_lines dl
JOIN units u ON u.id = dl.unit_id
LEFT JOIN products p ON p.id = dl.product_id
WHERE dl.tenant_id = $1 AND dl.document_id = $2
ORDER BY dl.line_number ASC
`

type ListDocumentLinesParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DocumentID pgtype.UUID `json:"document_id"`
}

type ListDocumentLinesRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	DocumentID  pgtype.UUID        `json:"document_id"`
	LineNumber  int32              `json:"line_number"`
	ProductID   pgtype.UUID        `json:"product_id"`
	Description string             `json:"description"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	UnitID      pgtype.UUID        `json:"unit_id"`
	UnitPrice   int64              `json:"unit_price"`
	Subtotal    int64              `json:"subtotal"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UnitCode    string             `json:"unit_code"`
	UnitSymbol  string             `json:"unit_symbol"`
	ProductName *string            `json:"product_name"`
}

func (q *Queries) ListDocumentLines(ctx context.Context, arg ListDocumentLinesParams) ([]ListDocumentLinesRow, error) {
	rows, err := q.db.Query(ctx, listDocumentLines, arg.TenantID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentLinesRow{}
	for rows.Next() {
		var i ListDocumentLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocumentID,
			&i.LineNumber,
			&i.ProductID,
			&i.Description,
			&i.Quantity,
			&i.UnitID,
			&i.UnitPrice,
			&i.Subtotal,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitCode,
			&i.UnitSymbol,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentTransitions = `-- name: ListDocumentTransitions :many
SELECT id, tenant_id, document_id, from_status, to_status, reason, actor_id, created_at FROM document_transitions
WHERE tenant_id = $1 AND document_id = $2
ORDER BY created_at ASC
`

type ListDocumentTransitionsParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	DocumentID pgtype.UUID `json:"document_id"`
}

func (q *Queries) ListDocumentTransitions(ctx context.Context, arg ListDocumentTransitionsParams) ([]DocumentTransition, error) {
	rows, err := q.db.Query(ctx, listDocumentTransitions, arg.TenantID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentTransition{}
	for rows.Next() {
		var i DocumentTransition
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DocumentID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Reason,
			&i.ActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT d.id, d.tenant_id, d.organization_id, d.document_type, d.document_number, d.document_date, d.party_id, d.status, d.total_amount, d.currency, d.notes, d.metadata, d.created_by, d.created_at, d.updated_at, o.name as organization_name, p.name as party_name
FROM documents d
JOIN organizations o ON o.id = d.organization_id
LEFT JOIN parties p ON p.id = d.party_id
WHERE d.tenant_id = $1
  AND ($4::uuid IS NULL OR d.organization_id = $4)
  AND ($5::varchar IS NULL OR d.document_type = $5)
  AND ($6::varchar IS NULL OR d.status = $6)
ORDER BY d.document_date DESC, d.created_at DESC
LIMIT $2 OFFSET $3
`

type ListDocumentsParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	DocumentType   *string     `json:"document_type"`
	Status         *string     `json:"status"`
}

type ListDocumentsRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	OrganizationID   pgtype.UUID        `json:"organization_id"`
	DocumentType     string             `json:"document_type"`
	DocumentNumber   string             `json:"document_number"`
	DocumentDate     pgtype.Date        `json:"document_date"`
	PartyID          pgtype.UUID        `json:"party_id"`
	Status           string             `json:"status"`
	TotalAmount      int64              `json:"total_amount"`
	Currency         string             `json:"currency"`
	Notes            *string            `json:"notes"`
	Metadata         []byte             `json:"metadata"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	OrganizationName string             `json:"organization_name"`
	PartyName        *string            `json:"party_name"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.OrganizationID,
		arg.DocumentType,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsRow{}
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrganizationID,
			&i.DocumentType,
			&i.DocumentNumber,
			&i.DocumentDate,
			&i.PartyID,
			&i.Status,
			&i.TotalAmount,
			&i.Currency,
			&i.Notes,
			&i.Metadata,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationName,
			&i.PartyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE documents
SET
    status = $3,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, organization_id, document_type, document_number, document_date, party_id, status, total_amount, currency, notes, metadata, created_by, created_at, updated_at
`

type UpdateDocumentStatusParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentStatus, arg.TenantID, arg.ID, arg.Status)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.DocumentDate,
		&i.PartyID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.Notes,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentTotal = `-- name: UpdateDocumentTotal :one
UPDATE documents
SET
    total_amount = $3,
    currency = $4,
    updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, organization_id, document_type, document_number, document_date, party_id, status, total_amount, currency, notes, metadata, created_by, created_at, updated_at
`

type UpdateDocumentTotalParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ID          pgtype.UUID `json:"id"`
	TotalAmount int64       `json:"total_amount"`
	Currency    string      `json:"currency"`
}

func (q *Queries) UpdateDocumentTotal(ctx context.Context, arg UpdateDocumentTotalParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentTotal,
		arg.TenantID,
		arg.ID,
		arg.TotalAmount,
		arg.Currency,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OrganizationID,
		&i.DocumentType,
		&i.DocumentNumber,
		&i.DocumentDate,
		&i.PartyID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.Notes,
		&i.Metadata,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
