// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFileReferences = `-- name: CountFileReferences :one
SELECT COUNT(*) FROM entity_attachments
WHERE tenant_id = $1 AND file_id = $2
`

type CountFileReferencesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	FileID   pgtype.UUID `json:"file_id"`
}

func (q *Queries) CountFileReferences(ctx context.Context, arg CountFileReferencesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFileReferences, arg.TenantID, arg.FileID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO entity_attachments (
    id, tenant_id, file_id, entity_type, entity_id, purpose, title, sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, file_id, entity_type, entity_id, purpose, title, sort_order, created_at
`

type CreateAttachmentParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	FileID     pgtype.UUID `json:"file_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Purpose    string      `json:"purpose"`
	Title      string      `json:"title"`
	SortOrder  int32       `json:"sort_order"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (EntityAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.ID,
		arg.TenantID,
		arg.FileID,
		arg.EntityType,
		arg.EntityID,
		arg.Purpose,
		arg.Title,
		arg.SortOrder,
	)
	var i EntityAttachment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FileID,
		&i.EntityType,
		&i.EntityID,
		&i.Purpose,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (
    id, tenant_id, storage_driver, storage_path, filename, mime_type,
    size_bytes, sha256_hash, uploaded_by, is_public, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, storage_driver, storage_path, filename, mime_type, size_bytes, sha256_hash, uploaded_by, is_public, metadata, created_at, updated_at
`

type CreateFileParams struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	StorageDriver string      `json:"storage_driver"`
	StoragePath   string      `json:"storage_path"`
	Filename      string      `json:"filename"`
	MimeType      string      `json:"mime_type"`
	SizeBytes     int64       `json:"size_bytes"`
	Sha256Hash    string      `json:"sha256_hash"`
	UploadedBy    pgtype.UUID `json:"uploaded_by"`
	IsPublic      bool        `json:"is_public"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.TenantID,
		arg.StorageDriver,
		arg.StoragePath,
		arg.Filename,
		arg.MimeType,
		arg.SizeBytes,
		arg.Sha256Hash,
		arg.UploadedBy,
		arg.IsPublic,
		arg.Metadata,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StorageDriver,
		&i.StoragePath,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256Hash,
		&i.UploadedBy,
		&i.IsPublic,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM entity_attachments
WHERE tenant_id = $1 AND id = $2
`

type DeleteAttachmentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.Exec(ctx, deleteAttachment, arg.TenantID, arg.ID)
	return err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files
WHERE tenant_id = $1 AND id = $2
`

type DeleteFileParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteFile(ctx context.Context, arg DeleteFileParams) error {
	_, err := q.db.Exec(ctx, deleteFile, arg.TenantID, arg.ID)
	return err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT id, tenant_id, file_id, entity_type, entity_id, purpose, title, sort_order, created_at FROM entity_attachments
WHERE tenant_id = $1 AND id = $2
`

type GetAttachmentByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetAttachmentByID(ctx context.Context, arg GetAttachmentByIDParams) (EntityAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, arg.TenantID, arg.ID)
	var i EntityAttachment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FileID,
		&i.EntityType,
		&i.EntityID,
		&i.Purpose,
		&i.Title,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getFileByHash = `-- name: GetFileByHash :one
SELECT id, tenant_id, storage_driver, storage_path, filename, mime_type, size_bytes, sha256_hash, uploaded_by, is_public, metadata, created_at, updated_at FROM files
WHERE tenant_id = $1 AND sha256_hash = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetFileByHashParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	Sha256Hash string      `json:"sha256_hash"`
}

func (q *Queries) GetFileByHash(ctx context.Context, arg GetFileByHashParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByHash, arg.TenantID, arg.Sha256Hash)
	var i File
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StorageDriver,
		&i.StoragePath,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256Hash,
		&i.UploadedBy,
		&i.IsPublic,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, tenant_id, storage_driver, storage_path, filename, mime_type, size_bytes, sha256_hash, uploaded_by, is_public, metadata, created_at, updated_at FROM files
WHERE tenant_id = $1 AND id = $2
`

type GetFileByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetFileByID(ctx context.Context, arg GetFileByIDParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, arg.TenantID, arg.ID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StorageDriver,
		&i.StoragePath,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.Sha256Hash,
		&i.UploadedBy,
		&i.IsPublic,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttachmentsByEntity = `-- name: ListAttachmentsByEntity :many
SELECT 
    ea.id AS attachment_id,
    ea.tenant_id,
    ea.file_id,
    ea.entity_type,
    ea.entity_id,
    ea.purpose,
    ea.title,
    ea.sort_order,
    ea.created_at AS attached_at,
    f.storage_driver,
    f.storage_path,
    f.filename,
    f.mime_type,
    f.size_bytes,
    f.sha256_hash,
    f.uploaded_by,
    f.is_public,
    f.metadata AS file_metadata,
    f.created_at AS file_created_at
FROM entity_attachments ea
JOIN files f ON ea.file_id = f.id
WHERE ea.tenant_id = $1 AND ea.entity_type = $2 AND ea.entity_id = $3
ORDER BY ea.sort_order ASC, ea.created_at ASC
`

type ListAttachmentsByEntityParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

type ListAttachmentsByEntityRow struct {
	AttachmentID  pgtype.UUID        `json:"attachment_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	FileID        pgtype.UUID        `json:"file_id"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	Purpose       string             `json:"purpose"`
	Title         string             `json:"title"`
	SortOrder     int32              `json:"sort_order"`
	AttachedAt    pgtype.Timestamptz `json:"attached_at"`
	StorageDriver string             `json:"storage_driver"`
	StoragePath   string             `json:"storage_path"`
	Filename      string             `json:"filename"`
	MimeType      string             `json:"mime_type"`
	SizeBytes     int64              `json:"size_bytes"`
	Sha256Hash    string             `json:"sha256_hash"`
	UploadedBy    pgtype.UUID        `json:"uploaded_by"`
	IsPublic      bool               `json:"is_public"`
	FileMetadata  []byte             `json:"file_metadata"`
	FileCreatedAt pgtype.Timestamptz `json:"file_created_at"`
}

func (q *Queries) ListAttachmentsByEntity(ctx context.Context, arg ListAttachmentsByEntityParams) ([]ListAttachmentsByEntityRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsByEntity, arg.TenantID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsByEntityRow{}
	for rows.Next() {
		var i ListAttachmentsByEntityRow
		if err := rows.Scan(
			&i.AttachmentID,
			&i.TenantID,
			&i.FileID,
			&i.EntityType,
			&i.EntityID,
			&i.Purpose,
			&i.Title,
			&i.SortOrder,
			&i.AttachedAt,
			&i.StorageDriver,
			&i.StoragePath,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.Sha256Hash,
			&i.UploadedBy,
			&i.IsPublic,
			&i.FileMetadata,
			&i.FileCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByTenant = `-- name: ListFilesByTenant :many
SELECT id, tenant_id, storage_driver, storage_path, filename, mime_type, size_bytes, sha256_hash, uploaded_by, is_public, metadata, created_at, updated_at FROM files
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListFilesByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListFilesByTenant(ctx context.Context, arg ListFilesByTenantParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listFilesByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.StorageDriver,
			&i.StoragePath,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.Sha256Hash,
			&i.UploadedBy,
			&i.IsPublic,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
