// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTenantMember = `-- name: AddTenantMember :one
INSERT INTO tenant_users (
    id, tenant_id, user_id, status, joined_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, tenant_id, user_id, status, joined_at
`

type AddTenantMemberParams struct {
	ID       pgtype.UUID        `json:"id"`
	TenantID pgtype.UUID        `json:"tenant_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Status   string             `json:"status"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) AddTenantMember(ctx context.Context, arg AddTenantMemberParams) (TenantUser, error) {
	row := q.db.QueryRow(ctx, addTenantMember,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Status,
		arg.JoinedAt,
	)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignPermissionToRoleParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO user_roles (tenant_id, user_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AssignUserRoleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	RoleID   pgtype.UUID `json:"role_id"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.TenantID, arg.UserID, arg.RoleID)
	return err
}

const clearRolePermissions = `-- name: ClearRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) ClearRolePermissions(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearRolePermissions, roleID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    id, tenant_id, code, name, description, is_system, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, code, name, description, is_system, created_at, updated_at
`

type CreateRoleParams struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IsSystem,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, password_hash, name, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, email, password_hash, name, status, created_at, updated_at
`

type CreateUserParams struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         string             `json:"name"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, tenant_id, code, name, description, is_system, created_at, updated_at FROM roles WHERE tenant_id = $1 AND code = $2
`

type GetRoleByCodeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetRoleByCode(ctx context.Context, arg GetRoleByCodeParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, arg.TenantID, arg.Code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, tenant_id, code, name, description, is_system, created_at, updated_at FROM roles WHERE tenant_id = $1 AND id = $2
`

type GetRoleByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetRoleByID(ctx context.Context, arg GetRoleByIDParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, arg.TenantID, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantMember = `-- name: GetTenantMember :one
SELECT id, tenant_id, user_id, status, joined_at FROM tenant_users 
WHERE tenant_id = $1 AND user_id = $2
`

type GetTenantMemberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetTenantMember(ctx context.Context, arg GetTenantMemberParams) (TenantUser, error) {
	row := q.db.QueryRow(ctx, getTenantMember, arg.TenantID, arg.UserID)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Status,
		&i.JoinedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, status, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, status, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, code, name, category, description FROM permissions ORDER BY category ASC, code ASC
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Category,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT p.id, p.code, p.name, p.category, p.description
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.code ASC
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Category,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, tenant_id, code, name, description, is_system, created_at, updated_at FROM roles WHERE tenant_id = $1 ORDER BY name ASC
`

func (q *Queries) ListRoles(ctx context.Context, tenantID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantUsers = `-- name: ListTenantUsers :many
SELECT 
    u.id AS user_id,
    u.email,
    u.name,
    u.status AS user_status,
    tu.status AS membership_status,
    tu.joined_at
FROM tenant_users tu
JOIN users u ON u.id = tu.user_id
WHERE tu.tenant_id = $1
ORDER BY tu.joined_at ASC
`

type ListTenantUsersRow struct {
	UserID           pgtype.UUID        `json:"user_id"`
	Email            string             `json:"email"`
	Name             string             `json:"name"`
	UserStatus       string             `json:"user_status"`
	MembershipStatus string             `json:"membership_status"`
	JoinedAt         pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListTenantUsers(ctx context.Context, tenantID pgtype.UUID) ([]ListTenantUsersRow, error) {
	rows, err := q.db.Query(ctx, listTenantUsers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantUsersRow{}
	for rows.Next() {
		var i ListTenantUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Name,
			&i.UserStatus,
			&i.MembershipStatus,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionsInTenant = `-- name: ListUserPermissionsInTenant :many
SELECT DISTINCT p.code
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
JOIN role_permissions rp ON rp.role_id = r.id
JOIN permissions p ON p.id = rp.permission_id
WHERE ur.tenant_id = $1 AND ur.user_id = $2
`

type ListUserPermissionsInTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListUserPermissionsInTenant(ctx context.Context, arg ListUserPermissionsInTenantParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissionsInTenant, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRolesInTenant = `-- name: ListUserRolesInTenant :many
SELECT r.id, r.code, r.name, r.description, r.is_system
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.tenant_id = $1 AND ur.user_id = $2
ORDER BY r.name ASC
`

type ListUserRolesInTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

type ListUserRolesInTenantRow struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	IsSystem    bool        `json:"is_system"`
}

func (q *Queries) ListUserRolesInTenant(ctx context.Context, arg ListUserRolesInTenantParams) ([]ListUserRolesInTenantRow, error) {
	rows, err := q.db.Query(ctx, listUserRolesInTenant, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRolesInTenantRow{}
	for rows.Next() {
		var i ListUserRolesInTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTenants = `-- name: ListUserTenants :many
SELECT 
    t.id AS tenant_id,
    t.code AS tenant_code,
    t.name AS tenant_name,
    t.status AS tenant_status,
    tu.status AS membership_status,
    tu.joined_at
FROM tenant_users tu
JOIN tenants t ON t.id = tu.tenant_id
WHERE tu.user_id = $1
ORDER BY tu.joined_at ASC
`

type ListUserTenantsRow struct {
	TenantID         pgtype.UUID        `json:"tenant_id"`
	TenantCode       string             `json:"tenant_code"`
	TenantName       string             `json:"tenant_name"`
	TenantStatus     string             `json:"tenant_status"`
	MembershipStatus string             `json:"membership_status"`
	JoinedAt         pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListUserTenants(ctx context.Context, userID pgtype.UUID) ([]ListUserTenantsRow, error) {
	rows, err := q.db.Query(ctx, listUserTenants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserTenantsRow{}
	for rows.Next() {
		var i ListUserTenantsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.TenantCode,
			&i.TenantName,
			&i.TenantStatus,
			&i.MembershipStatus,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserRole = `-- name: RemoveUserRole :exec
DELETE FROM user_roles
WHERE tenant_id = $1 AND user_id = $2 AND role_id = $3
`

type RemoveUserRoleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	RoleID   pgtype.UUID `json:"role_id"`
}

func (q *Queries) RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error {
	_, err := q.db.Exec(ctx, removeUserRole, arg.TenantID, arg.UserID, arg.RoleID)
	return err
}
