// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Address struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Type        string             `json:"type"`
	Label       *string            `json:"label"`
	Line1       string             `json:"line1"`
	Line2       *string            `json:"line2"`
	City        string             `json:"city"`
	State       *string            `json:"state"`
	PostalCode  *string            `json:"postal_code"`
	CountryCode string             `json:"country_code"`
	Latitude    pgtype.Numeric     `json:"latitude"`
	Longitude   pgtype.Numeric     `json:"longitude"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Contact struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	PartyID        pgtype.UUID        `json:"party_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Type           string             `json:"type"`
	Value          string             `json:"value"`
	Label          *string            `json:"label"`
	IsPrimary      bool               `json:"is_primary"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Document struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	DocumentType   string             `json:"document_type"`
	DocumentNumber string             `json:"document_number"`
	DocumentDate   pgtype.Date        `json:"document_date"`
	PartyID        pgtype.UUID        `json:"party_id"`
	Status         string             `json:"status"`
	TotalAmount    int64              `json:"total_amount"`
	Currency       string             `json:"currency"`
	Notes          *string            `json:"notes"`
	Metadata       []byte             `json:"metadata"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DocumentLine struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	DocumentID  pgtype.UUID        `json:"document_id"`
	LineNumber  int32              `json:"line_number"`
	ProductID   pgtype.UUID        `json:"product_id"`
	Description string             `json:"description"`
	Quantity    pgtype.Numeric     `json:"quantity"`
	UnitID      pgtype.UUID        `json:"unit_id"`
	UnitPrice   int64              `json:"unit_price"`
	Subtotal    int64              `json:"subtotal"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type DocumentTransition struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	DocumentID pgtype.UUID        `json:"document_id"`
	FromStatus string             `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	Reason     *string            `json:"reason"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	LegalName *string            `json:"legal_name"`
	Type      string             `json:"type"`
	Status    string             `json:"status"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationAddress struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	AddressID      pgtype.UUID        `json:"address_id"`
	AddressType    string             `json:"address_type"`
	IsPrimary      bool               `json:"is_primary"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Party struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Type      string             `json:"type"`
	Code      *string            `json:"code"`
	Name      string             `json:"name"`
	LegalName *string            `json:"legal_name"`
	TaxID     *string            `json:"tax_id"`
	Status    string             `json:"status"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type PartyAddress struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	PartyID     pgtype.UUID        `json:"party_id"`
	AddressID   pgtype.UUID        `json:"address_id"`
	AddressType string             `json:"address_type"`
	IsPrimary   bool               `json:"is_primary"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PartyRole struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	PartyID        pgtype.UUID        `json:"party_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	RoleType       string             `json:"role_type"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Type        string             `json:"type"`
	Sku         *string            `json:"sku"`
	Barcode     *string            `json:"barcode"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	UnitID      pgtype.UUID        `json:"unit_id"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ProductVariant struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ProductID  pgtype.UUID        `json:"product_id"`
	Sku        string             `json:"sku"`
	Name       string             `json:"name"`
	Attributes []byte             `json:"attributes"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Unit struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Symbol    string             `json:"symbol"`
	Category  string             `json:"category"`
	Precision int32              `json:"precision"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UnitConversion struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	FromUnitID pgtype.UUID        `json:"from_unit_id"`
	ToUnitID   pgtype.UUID        `json:"to_unit_id"`
	Factor     pgtype.Numeric     `json:"factor"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
