// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (
    id,
    tenant_id,
    parent_id,
    code,
    name,
    legal_name,
    type,
    status,
    settings,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, parent_id, code, name, legal_name, type, status, settings, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	LegalName *string            `json:"legal_name"`
	Type      string             `json:"type"`
	Status    string             `json:"status"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.TenantID,
		arg.ParentID,
		arg.Code,
		arg.Name,
		arg.LegalName,
		arg.Type,
		arg.Status,
		arg.Settings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Type,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByCode = `-- name: GetOrganizationByCode :one
SELECT id, tenant_id, parent_id, code, name, legal_name, type, status, settings, created_at, updated_at FROM organizations
WHERE tenant_id = $1 AND code = $2 LIMIT 1
`

type GetOrganizationByCodeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetOrganizationByCode(ctx context.Context, arg GetOrganizationByCodeParams) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByCode, arg.TenantID, arg.Code)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Type,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, tenant_id, parent_id, code, name, legal_name, type, status, settings, created_at, updated_at FROM organizations
WHERE tenant_id = $1 AND id = $2 LIMIT 1
`

type GetOrganizationByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetOrganizationByID(ctx context.Context, arg GetOrganizationByIDParams) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, arg.TenantID, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Type,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationChildren = `-- name: ListOrganizationChildren :many
SELECT id, tenant_id, parent_id, code, name, legal_name, type, status, settings, created_at, updated_at FROM organizations
WHERE tenant_id = $1 AND parent_id = $2
ORDER BY name ASC
`

type ListOrganizationChildrenParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ParentID pgtype.UUID `json:"parent_id"`
}

func (q *Queries) ListOrganizationChildren(ctx context.Context, arg ListOrganizationChildrenParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationChildren, arg.TenantID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.LegalName,
			&i.Type,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsByTenant = `-- name: ListOrganizationsByTenant :many
SELECT id, tenant_id, parent_id, code, name, legal_name, type, status, settings, created_at, updated_at FROM organizations
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrganizationsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ParentID,
			&i.Code,
			&i.Name,
			&i.LegalName,
			&i.Type,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET
    parent_id = COALESCE($1, parent_id),
    name = COALESCE($2, name),
    legal_name = COALESCE($3, legal_name),
    type = COALESCE($4, type),
    status = COALESCE($5, status),
    settings = COALESCE($6, settings),
    updated_at = NOW()
WHERE tenant_id = $7 AND id = $8
RETURNING id, tenant_id, parent_id, code, name, legal_name, type, status, settings, created_at, updated_at
`

type UpdateOrganizationParams struct {
	ParentID  pgtype.UUID `json:"parent_id"`
	Name      *string     `json:"name"`
	LegalName *string     `json:"legal_name"`
	Type      *string     `json:"type"`
	Status    *string     `json:"status"`
	Settings  []byte      `json:"settings"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization,
		arg.ParentID,
		arg.Name,
		arg.LegalName,
		arg.Type,
		arg.Status,
		arg.Settings,
		arg.TenantID,
		arg.ID,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ParentID,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.Type,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
