// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    id, tenant_id, event_type, aggregate_type, aggregate_id, payload, status, retry_count, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, tenant_id, event_type, aggregate_type, aggregate_id, payload, status, retry_count, error_message, created_at, published_at
`

type CreateOutboxEventParams struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	RetryCount    int32              `json:"retry_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.ID,
		arg.TenantID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.Status,
		arg.RetryCount,
		arg.CreatedAt,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.Status,
		&i.RetryCount,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const fetchPendingOutboxEvents = `-- name: FetchPendingOutboxEvents :many
SELECT 
    id, tenant_id, event_type, aggregate_type, aggregate_id, payload, status, retry_count, error_message, created_at, published_at
FROM outbox_events
WHERE status IN ('pending', 'failed')
  AND retry_count < $1
ORDER BY created_at ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type FetchPendingOutboxEventsParams struct {
	RetryCount int32 `json:"retry_count"`
	Limit      int32 `json:"limit"`
}

func (q *Queries) FetchPendingOutboxEvents(ctx context.Context, arg FetchPendingOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, fetchPendingOutboxEvents, arg.RetryCount, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Status,
			&i.RetryCount,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET status = 'failed',
    retry_count = retry_count + 1,
    error_message = $2
WHERE id = $1
`

type MarkOutboxEventFailedParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorMessage *string     `json:"error_message"`
}

func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET status = 'published',
    published_at = $2,
    error_message = NULL
WHERE id = $1
`

type MarkOutboxEventPublishedParams struct {
	ID          pgtype.UUID        `json:"id"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, arg MarkOutboxEventPublishedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, arg.ID, arg.PublishedAt)
	return err
}
