// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: parties.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countParties = `-- name: CountParties :one
SELECT COUNT(*) FROM parties
WHERE tenant_id = $1
  AND ($2::varchar IS NULL OR type = $2)
`

type CountPartiesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Type     *string     `json:"type"`
}

func (q *Queries) CountParties(ctx context.Context, arg CountPartiesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countParties, arg.TenantID, arg.Type)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPartiesByRole = `-- name: CountPartiesByRole :one
SELECT COUNT(DISTINCT p.id) FROM parties p
JOIN party_roles pr ON pr.party_id = p.id AND pr.tenant_id = p.tenant_id
WHERE p.tenant_id = $1 AND pr.role_type = $2 AND pr.status = 'active'
`

type CountPartiesByRoleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	RoleType string      `json:"role_type"`
}

func (q *Queries) CountPartiesByRole(ctx context.Context, arg CountPartiesByRoleParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPartiesByRole, arg.TenantID, arg.RoleType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createParty = `-- name: CreateParty :one
INSERT INTO parties (
    id,
    tenant_id,
    type,
    code,
    name,
    legal_name,
    tax_id,
    status,
    metadata,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, tenant_id, type, code, name, legal_name, tax_id, status, metadata, created_at, updated_at
`

type CreatePartyParams struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Type      string             `json:"type"`
	Code      *string            `json:"code"`
	Name      string             `json:"name"`
	LegalName *string            `json:"legal_name"`
	TaxID     *string            `json:"tax_id"`
	Status    string             `json:"status"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateParty(ctx context.Context, arg CreatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, createParty,
		arg.ID,
		arg.TenantID,
		arg.Type,
		arg.Code,
		arg.Name,
		arg.LegalName,
		arg.TaxID,
		arg.Status,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.TaxID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPartyRole = `-- name: CreatePartyRole :one
INSERT INTO party_roles (
    id,
    tenant_id,
    party_id,
    organization_id,
    role_type,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, party_id, organization_id, role_type, status, created_at, updated_at
`

type CreatePartyRoleParams struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	PartyID        pgtype.UUID        `json:"party_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	RoleType       string             `json:"role_type"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePartyRole(ctx context.Context, arg CreatePartyRoleParams) (PartyRole, error) {
	row := q.db.QueryRow(ctx, createPartyRole,
		arg.ID,
		arg.TenantID,
		arg.PartyID,
		arg.OrganizationID,
		arg.RoleType,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i PartyRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PartyID,
		&i.OrganizationID,
		&i.RoleType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePartyRole = `-- name: DeletePartyRole :exec
DELETE FROM party_roles
WHERE tenant_id = $1 AND id = $2
`

type DeletePartyRoleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeletePartyRole(ctx context.Context, arg DeletePartyRoleParams) error {
	_, err := q.db.Exec(ctx, deletePartyRole, arg.TenantID, arg.ID)
	return err
}

const getPartyByID = `-- name: GetPartyByID :one
SELECT id, tenant_id, type, code, name, legal_name, tax_id, status, metadata, created_at, updated_at FROM parties
WHERE tenant_id = $1 AND id = $2 LIMIT 1
`

type GetPartyByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetPartyByID(ctx context.Context, arg GetPartyByIDParams) (Party, error) {
	row := q.db.QueryRow(ctx, getPartyByID, arg.TenantID, arg.ID)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.TaxID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listParties = `-- name: ListParties :many
SELECT id, tenant_id, type, code, name, legal_name, tax_id, status, metadata, created_at, updated_at FROM parties
WHERE tenant_id = $1
  AND ($4::varchar IS NULL OR type = $4)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPartiesParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Type     *string     `json:"type"`
}

func (q *Queries) ListParties(ctx context.Context, arg ListPartiesParams) ([]Party, error) {
	rows, err := q.db.Query(ctx, listParties,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Type,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Party{}
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Code,
			&i.Name,
			&i.LegalName,
			&i.TaxID,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartiesByRole = `-- name: ListPartiesByRole :many
SELECT p.id, p.tenant_id, p.type, p.code, p.name, p.legal_name, p.tax_id, p.status, p.metadata, p.created_at, p.updated_at FROM parties p
JOIN party_roles pr ON pr.party_id = p.id AND pr.tenant_id = p.tenant_id
WHERE p.tenant_id = $1 AND pr.role_type = $2 AND pr.status = 'active'
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $4
`

type ListPartiesByRoleParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	RoleType string      `json:"role_type"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListPartiesByRole(ctx context.Context, arg ListPartiesByRoleParams) ([]Party, error) {
	rows, err := q.db.Query(ctx, listPartiesByRole,
		arg.TenantID,
		arg.RoleType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Party{}
	for rows.Next() {
		var i Party
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Code,
			&i.Name,
			&i.LegalName,
			&i.TaxID,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByPartyID = `-- name: ListRolesByPartyID :many
SELECT id, tenant_id, party_id, organization_id, role_type, status, created_at, updated_at FROM party_roles
WHERE tenant_id = $1 AND party_id = $2
ORDER BY created_at ASC
`

type ListRolesByPartyIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	PartyID  pgtype.UUID `json:"party_id"`
}

func (q *Queries) ListRolesByPartyID(ctx context.Context, arg ListRolesByPartyIDParams) ([]PartyRole, error) {
	rows, err := q.db.Query(ctx, listRolesByPartyID, arg.TenantID, arg.PartyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PartyRole{}
	for rows.Next() {
		var i PartyRole
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PartyID,
			&i.OrganizationID,
			&i.RoleType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParty = `-- name: UpdateParty :one
UPDATE parties
SET
    name = COALESCE($1, name),
    legal_name = COALESCE($2, legal_name),
    tax_id = COALESCE($3, tax_id),
    status = COALESCE($4, status),
    metadata = COALESCE($5, metadata),
    updated_at = NOW()
WHERE tenant_id = $6 AND id = $7
RETURNING id, tenant_id, type, code, name, legal_name, tax_id, status, metadata, created_at, updated_at
`

type UpdatePartyParams struct {
	Name      *string     `json:"name"`
	LegalName *string     `json:"legal_name"`
	TaxID     *string     `json:"tax_id"`
	Status    *string     `json:"status"`
	Metadata  []byte      `json:"metadata"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateParty(ctx context.Context, arg UpdatePartyParams) (Party, error) {
	row := q.db.QueryRow(ctx, updateParty,
		arg.Name,
		arg.LegalName,
		arg.TaxID,
		arg.Status,
		arg.Metadata,
		arg.TenantID,
		arg.ID,
	)
	var i Party
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Code,
		&i.Name,
		&i.LegalName,
		&i.TaxID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
