// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
WHERE tenant_id = $1
  AND ($2::varchar IS NULL OR type = $2)
  AND ($3::varchar IS NULL OR status = $3)
`

type CountProductsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Type     *string     `json:"type"`
	Status   *string     `json:"status"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.TenantID, arg.Type, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    id,
    tenant_id,
    type,
    sku,
    barcode,
    name,
    description,
    unit_id,
    status,
    metadata,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, tenant_id, type, sku, barcode, name, description, unit_id, status, metadata, created_at, updated_at
`

type CreateProductParams struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Type        string             `json:"type"`
	Sku         *string            `json:"sku"`
	Barcode     *string            `json:"barcode"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	UnitID      pgtype.UUID        `json:"unit_id"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.TenantID,
		arg.Type,
		arg.Sku,
		arg.Barcode,
		arg.Name,
		arg.Description,
		arg.UnitID,
		arg.Status,
		arg.Metadata,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Description,
		&i.UnitID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (
    id,
    tenant_id,
    product_id,
    sku,
    name,
    attributes,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, tenant_id, product_id, sku, name, attributes, status, created_at, updated_at
`

type CreateProductVariantParams struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ProductID  pgtype.UUID        `json:"product_id"`
	Sku        string             `json:"sku"`
	Name       string             `json:"name"`
	Attributes []byte             `json:"attributes"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.ID,
		arg.TenantID,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.Attributes,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Attributes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (
    id,
    tenant_id,
    code,
    name,
    symbol,
    category,
    precision,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, tenant_id, code, name, symbol, category, precision, status, created_at, updated_at
`

type CreateUnitParams struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Symbol    string             `json:"symbol"`
	Category  string             `json:"category"`
	Precision int32              `json:"precision"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Symbol,
		arg.Category,
		arg.Precision,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Category,
		&i.Precision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUnitConversion = `-- name: CreateUnitConversion :one
INSERT INTO unit_conversions (
    id,
    tenant_id,
    from_unit_id,
    to_unit_id,
    factor,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, from_unit_id, to_unit_id, factor, created_at, updated_at
`

type CreateUnitConversionParams struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	FromUnitID pgtype.UUID        `json:"from_unit_id"`
	ToUnitID   pgtype.UUID        `json:"to_unit_id"`
	Factor     pgtype.Numeric     `json:"factor"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUnitConversion(ctx context.Context, arg CreateUnitConversionParams) (UnitConversion, error) {
	row := q.db.QueryRow(ctx, createUnitConversion,
		arg.ID,
		arg.TenantID,
		arg.FromUnitID,
		arg.ToUnitID,
		arg.Factor,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UnitConversion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FromUnitID,
		&i.ToUnitID,
		&i.Factor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE FROM product_variants
WHERE tenant_id = $1 AND id = $2
`

type DeleteProductVariantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteProductVariant(ctx context.Context, arg DeleteProductVariantParams) error {
	_, err := q.db.Exec(ctx, deleteProductVariant, arg.TenantID, arg.ID)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT p.id, p.tenant_id, p.type, p.sku, p.barcode, p.name, p.description, p.unit_id, p.status, p.metadata, p.created_at, p.updated_at, u.code as unit_code, u.name as unit_name, u.symbol as unit_symbol
FROM products p
JOIN units u ON u.id = p.unit_id
WHERE p.tenant_id = $1 AND p.id = $2 LIMIT 1
`

type GetProductByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetProductByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Type        string             `json:"type"`
	Sku         *string            `json:"sku"`
	Barcode     *string            `json:"barcode"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	UnitID      pgtype.UUID        `json:"unit_id"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UnitCode    string             `json:"unit_code"`
	UnitName    string             `json:"unit_name"`
	UnitSymbol  string             `json:"unit_symbol"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (GetProductByIDRow, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.TenantID, arg.ID)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Description,
		&i.UnitID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnitCode,
		&i.UnitName,
		&i.UnitSymbol,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT p.id, p.tenant_id, p.type, p.sku, p.barcode, p.name, p.description, p.unit_id, p.status, p.metadata, p.created_at, p.updated_at, u.code as unit_code, u.name as unit_name, u.symbol as unit_symbol
FROM products p
JOIN units u ON u.id = p.unit_id
WHERE p.tenant_id = $1 AND p.sku = $2 LIMIT 1
`

type GetProductBySKUParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Sku      *string     `json:"sku"`
}

type GetProductBySKURow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Type        string             `json:"type"`
	Sku         *string            `json:"sku"`
	Barcode     *string            `json:"barcode"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	UnitID      pgtype.UUID        `json:"unit_id"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UnitCode    string             `json:"unit_code"`
	UnitName    string             `json:"unit_name"`
	UnitSymbol  string             `json:"unit_symbol"`
}

func (q *Queries) GetProductBySKU(ctx context.Context, arg GetProductBySKUParams) (GetProductBySKURow, error) {
	row := q.db.QueryRow(ctx, getProductBySKU, arg.TenantID, arg.Sku)
	var i GetProductBySKURow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Description,
		&i.UnitID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UnitCode,
		&i.UnitName,
		&i.UnitSymbol,
	)
	return i, err
}

const getUnitByCode = `-- name: GetUnitByCode :one
SELECT id, tenant_id, code, name, symbol, category, precision, status, created_at, updated_at FROM units
WHERE tenant_id = $1 AND code = $2 LIMIT 1
`

type GetUnitByCodeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetUnitByCode(ctx context.Context, arg GetUnitByCodeParams) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByCode, arg.TenantID, arg.Code)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Category,
		&i.Precision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT id, tenant_id, code, name, symbol, category, precision, status, created_at, updated_at FROM units
WHERE tenant_id = $1 AND id = $2 LIMIT 1
`

type GetUnitByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetUnitByID(ctx context.Context, arg GetUnitByIDParams) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByID, arg.TenantID, arg.ID)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.Category,
		&i.Precision,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitConversion = `-- name: GetUnitConversion :one
SELECT id, tenant_id, from_unit_id, to_unit_id, factor, created_at, updated_at FROM unit_conversions
WHERE tenant_id = $1 AND from_unit_id = $2 AND to_unit_id = $3 LIMIT 1
`

type GetUnitConversionParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	FromUnitID pgtype.UUID `json:"from_unit_id"`
	ToUnitID   pgtype.UUID `json:"to_unit_id"`
}

func (q *Queries) GetUnitConversion(ctx context.Context, arg GetUnitConversionParams) (UnitConversion, error) {
	row := q.db.QueryRow(ctx, getUnitConversion, arg.TenantID, arg.FromUnitID, arg.ToUnitID)
	var i UnitConversion
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.FromUnitID,
		&i.ToUnitID,
		&i.Factor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductVariants = `-- name: ListProductVariants :many
SELECT id, tenant_id, product_id, sku, name, attributes, status, created_at, updated_at FROM product_variants
WHERE tenant_id = $1 AND product_id = $2
ORDER BY sku ASC
`

type ListProductVariantsParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ProductID pgtype.UUID `json:"product_id"`
}

func (q *Queries) ListProductVariants(ctx context.Context, arg ListProductVariantsParams) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listProductVariants, arg.TenantID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductVariant{}
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.Attributes,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.tenant_id, p.type, p.sku, p.barcode, p.name, p.description, p.unit_id, p.status, p.metadata, p.created_at, p.updated_at, u.code as unit_code, u.symbol as unit_symbol
FROM products p
JOIN units u ON u.id = p.unit_id
WHERE p.tenant_id = $1
  AND ($4::varchar IS NULL OR p.type = $4)
  AND ($5::varchar IS NULL OR p.status = $5)
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
	Type     *string     `json:"type"`
	Status   *string     `json:"status"`
}

type ListProductsRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Type        string             `json:"type"`
	Sku         *string            `json:"sku"`
	Barcode     *string            `json:"barcode"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	UnitID      pgtype.UUID        `json:"unit_id"`
	Status      string             `json:"status"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UnitCode    string             `json:"unit_code"`
	UnitSymbol  string             `json:"unit_symbol"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Type,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Type,
			&i.Sku,
			&i.Barcode,
			&i.Name,
			&i.Description,
			&i.UnitID,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UnitCode,
			&i.UnitSymbol,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitConversions = `-- name: ListUnitConversions :many
SELECT uc.id, uc.tenant_id, uc.from_unit_id, uc.to_unit_id, uc.factor, uc.created_at, uc.updated_at, u1.code as from_code, u2.code as to_code
FROM unit_conversions uc
JOIN units u1 ON u1.id = uc.from_unit_id
JOIN units u2 ON u2.id = uc.to_unit_id
WHERE uc.tenant_id = $1
ORDER BY uc.created_at ASC
`

type ListUnitConversionsRow struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	FromUnitID pgtype.UUID        `json:"from_unit_id"`
	ToUnitID   pgtype.UUID        `json:"to_unit_id"`
	Factor     pgtype.Numeric     `json:"factor"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	FromCode   string             `json:"from_code"`
	ToCode     string             `json:"to_code"`
}

func (q *Queries) ListUnitConversions(ctx context.Context, tenantID pgtype.UUID) ([]ListUnitConversionsRow, error) {
	rows, err := q.db.Query(ctx, listUnitConversions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitConversionsRow{}
	for rows.Next() {
		var i ListUnitConversionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.FromUnitID,
			&i.ToUnitID,
			&i.Factor,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FromCode,
			&i.ToCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT id, tenant_id, code, name, symbol, category, precision, status, created_at, updated_at FROM units
WHERE tenant_id = $1
ORDER BY code ASC
`

func (q *Queries) ListUnits(ctx context.Context, tenantID pgtype.UUID) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.Category,
			&i.Precision,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    barcode = COALESCE($3, barcode),
    status = COALESCE($4, status),
    metadata = COALESCE($5, metadata),
    updated_at = NOW()
WHERE tenant_id = $6 AND id = $7
RETURNING id, tenant_id, type, sku, barcode, name, description, unit_id, status, metadata, created_at, updated_at
`

type UpdateProductParams struct {
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Barcode     *string     `json:"barcode"`
	Status      *string     `json:"status"`
	Metadata    []byte      `json:"metadata"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Description,
		arg.Barcode,
		arg.Status,
		arg.Metadata,
		arg.TenantID,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Type,
		&i.Sku,
		&i.Barcode,
		&i.Name,
		&i.Description,
		&i.UnitID,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
