// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sequences.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSequence = `-- name: CreateSequence :one
INSERT INTO number_sequences (
    id, tenant_id, code, name, entity_type, sub_type,
    prefix, suffix, template, padding, start_value,
    increment_by, current_value, reset_policy,
    last_number, last_reset_at, is_active, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17, $18, $19
) RETURNING id, tenant_id, code, name, entity_type, sub_type, prefix, suffix, template, padding, start_value, increment_by, current_value, reset_policy, last_number, last_reset_at, is_active, created_at, updated_at
`

type CreateSequenceParams struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	EntityType   string             `json:"entity_type"`
	SubType      string             `json:"sub_type"`
	Prefix       string             `json:"prefix"`
	Suffix       string             `json:"suffix"`
	Template     string             `json:"template"`
	Padding      int32              `json:"padding"`
	StartValue   int64              `json:"start_value"`
	IncrementBy  int32              `json:"increment_by"`
	CurrentValue int64              `json:"current_value"`
	ResetPolicy  string             `json:"reset_policy"`
	LastNumber   *string            `json:"last_number"`
	LastResetAt  pgtype.Timestamptz `json:"last_reset_at"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSequence(ctx context.Context, arg CreateSequenceParams) (NumberSequence, error) {
	row := q.db.QueryRow(ctx, createSequence,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.EntityType,
		arg.SubType,
		arg.Prefix,
		arg.Suffix,
		arg.Template,
		arg.Padding,
		arg.StartValue,
		arg.IncrementBy,
		arg.CurrentValue,
		arg.ResetPolicy,
		arg.LastNumber,
		arg.LastResetAt,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i NumberSequence
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.EntityType,
		&i.SubType,
		&i.Prefix,
		&i.Suffix,
		&i.Template,
		&i.Padding,
		&i.StartValue,
		&i.IncrementBy,
		&i.CurrentValue,
		&i.ResetPolicy,
		&i.LastNumber,
		&i.LastResetAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSequence = `-- name: DeleteSequence :exec
DELETE FROM number_sequences
WHERE tenant_id = $1 AND id = $2
`

type DeleteSequenceParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeleteSequence(ctx context.Context, arg DeleteSequenceParams) error {
	_, err := q.db.Exec(ctx, deleteSequence, arg.TenantID, arg.ID)
	return err
}

const getSequenceByCode = `-- name: GetSequenceByCode :one
SELECT id, tenant_id, code, name, entity_type, sub_type, prefix, suffix, template, padding, start_value, increment_by, current_value, reset_policy, last_number, last_reset_at, is_active, created_at, updated_at FROM number_sequences
WHERE tenant_id = $1 AND code = $2
`

type GetSequenceByCodeParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

func (q *Queries) GetSequenceByCode(ctx context.Context, arg GetSequenceByCodeParams) (NumberSequence, error) {
	row := q.db.QueryRow(ctx, getSequenceByCode, arg.TenantID, arg.Code)
	var i NumberSequence
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.EntityType,
		&i.SubType,
		&i.Prefix,
		&i.Suffix,
		&i.Template,
		&i.Padding,
		&i.StartValue,
		&i.IncrementBy,
		&i.CurrentValue,
		&i.ResetPolicy,
		&i.LastNumber,
		&i.LastResetAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSequenceByEntity = `-- name: GetSequenceByEntity :one
SELECT id, tenant_id, code, name, entity_type, sub_type, prefix, suffix, template, padding, start_value, increment_by, current_value, reset_policy, last_number, last_reset_at, is_active, created_at, updated_at FROM number_sequences
WHERE tenant_id = $1 AND entity_type = $2 AND sub_type = $3 AND is_active = true
`

type GetSequenceByEntityParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
	SubType    string      `json:"sub_type"`
}

func (q *Queries) GetSequenceByEntity(ctx context.Context, arg GetSequenceByEntityParams) (NumberSequence, error) {
	row := q.db.QueryRow(ctx, getSequenceByEntity, arg.TenantID, arg.EntityType, arg.SubType)
	var i NumberSequence
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.EntityType,
		&i.SubType,
		&i.Prefix,
		&i.Suffix,
		&i.Template,
		&i.Padding,
		&i.StartValue,
		&i.IncrementBy,
		&i.CurrentValue,
		&i.ResetPolicy,
		&i.LastNumber,
		&i.LastResetAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSequenceByID = `-- name: GetSequenceByID :one
SELECT id, tenant_id, code, name, entity_type, sub_type, prefix, suffix, template, padding, start_value, increment_by, current_value, reset_policy, last_number, last_reset_at, is_active, created_at, updated_at FROM number_sequences
WHERE tenant_id = $1 AND id = $2
`

type GetSequenceByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetSequenceByID(ctx context.Context, arg GetSequenceByIDParams) (NumberSequence, error) {
	row := q.db.QueryRow(ctx, getSequenceByID, arg.TenantID, arg.ID)
	var i NumberSequence
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.EntityType,
		&i.SubType,
		&i.Prefix,
		&i.Suffix,
		&i.Template,
		&i.Padding,
		&i.StartValue,
		&i.IncrementBy,
		&i.CurrentValue,
		&i.ResetPolicy,
		&i.LastNumber,
		&i.LastResetAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSequenceByIDForUpdate = `-- name: GetSequenceByIDForUpdate :one
SELECT id, tenant_id, code, name, entity_type, sub_type, prefix, suffix, template, padding, start_value, increment_by, current_value, reset_policy, last_number, last_reset_at, is_active, created_at, updated_at FROM number_sequences
WHERE tenant_id = $1 AND id = $2 AND is_active = true
FOR UPDATE
`

type GetSequenceByIDForUpdateParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetSequenceByIDForUpdate(ctx context.Context, arg GetSequenceByIDForUpdateParams) (NumberSequence, error) {
	row := q.db.QueryRow(ctx, getSequenceByIDForUpdate, arg.TenantID, arg.ID)
	var i NumberSequence
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.EntityType,
		&i.SubType,
		&i.Prefix,
		&i.Suffix,
		&i.Template,
		&i.Padding,
		&i.StartValue,
		&i.IncrementBy,
		&i.CurrentValue,
		&i.ResetPolicy,
		&i.LastNumber,
		&i.LastResetAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSequenceForUpdate = `-- name: GetSequenceForUpdate :one
SELECT id, tenant_id, code, name, entity_type, sub_type, prefix, suffix, template, padding, start_value, increment_by, current_value, reset_policy, last_number, last_reset_at, is_active, created_at, updated_at FROM number_sequences
WHERE tenant_id = $1 AND entity_type = $2 AND sub_type = $3 AND is_active = true
FOR UPDATE
`

type GetSequenceForUpdateParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	EntityType string      `json:"entity_type"`
	SubType    string      `json:"sub_type"`
}

func (q *Queries) GetSequenceForUpdate(ctx context.Context, arg GetSequenceForUpdateParams) (NumberSequence, error) {
	row := q.db.QueryRow(ctx, getSequenceForUpdate, arg.TenantID, arg.EntityType, arg.SubType)
	var i NumberSequence
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.EntityType,
		&i.SubType,
		&i.Prefix,
		&i.Suffix,
		&i.Template,
		&i.Padding,
		&i.StartValue,
		&i.IncrementBy,
		&i.CurrentValue,
		&i.ResetPolicy,
		&i.LastNumber,
		&i.LastResetAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSequences = `-- name: ListSequences :many
SELECT id, tenant_id, code, name, entity_type, sub_type, prefix, suffix, template, padding, start_value, increment_by, current_value, reset_policy, last_number, last_reset_at, is_active, created_at, updated_at FROM number_sequences
WHERE tenant_id = $1
ORDER BY entity_type ASC, sub_type ASC, code ASC
`

func (q *Queries) ListSequences(ctx context.Context, tenantID pgtype.UUID) ([]NumberSequence, error) {
	rows, err := q.db.Query(ctx, listSequences, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NumberSequence{}
	for rows.Next() {
		var i NumberSequence
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.EntityType,
			&i.SubType,
			&i.Prefix,
			&i.Suffix,
			&i.Template,
			&i.Padding,
			&i.StartValue,
			&i.IncrementBy,
			&i.CurrentValue,
			&i.ResetPolicy,
			&i.LastNumber,
			&i.LastResetAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSequence = `-- name: UpdateSequence :one
UPDATE number_sequences
SET name = $3,
    prefix = $4,
    suffix = $5,
    template = $6,
    padding = $7,
    reset_policy = $8,
    is_active = $9,
    updated_at = $10
WHERE tenant_id = $1 AND id = $2
RETURNING id, tenant_id, code, name, entity_type, sub_type, prefix, suffix, template, padding, start_value, increment_by, current_value, reset_policy, last_number, last_reset_at, is_active, created_at, updated_at
`

type UpdateSequenceParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Prefix      string             `json:"prefix"`
	Suffix      string             `json:"suffix"`
	Template    string             `json:"template"`
	Padding     int32              `json:"padding"`
	ResetPolicy string             `json:"reset_policy"`
	IsActive    bool               `json:"is_active"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSequence(ctx context.Context, arg UpdateSequenceParams) (NumberSequence, error) {
	row := q.db.QueryRow(ctx, updateSequence,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Prefix,
		arg.Suffix,
		arg.Template,
		arg.Padding,
		arg.ResetPolicy,
		arg.IsActive,
		arg.UpdatedAt,
	)
	var i NumberSequence
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.EntityType,
		&i.SubType,
		&i.Prefix,
		&i.Suffix,
		&i.Template,
		&i.Padding,
		&i.StartValue,
		&i.IncrementBy,
		&i.CurrentValue,
		&i.ResetPolicy,
		&i.LastNumber,
		&i.LastResetAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSequenceValue = `-- name: UpdateSequenceValue :exec
UPDATE number_sequences
SET current_value = $3,
    last_number = $4,
    last_reset_at = $5,
    updated_at = $6
WHERE tenant_id = $1 AND id = $2
`

type UpdateSequenceValueParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ID           pgtype.UUID        `json:"id"`
	CurrentValue int64              `json:"current_value"`
	LastNumber   *string            `json:"last_number"`
	LastResetAt  pgtype.Timestamptz `json:"last_reset_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSequenceValue(ctx context.Context, arg UpdateSequenceValueParams) error {
	_, err := q.db.Exec(ctx, updateSequenceValue,
		arg.TenantID,
		arg.ID,
		arg.CurrentValue,
		arg.LastNumber,
		arg.LastResetAt,
		arg.UpdatedAt,
	)
	return err
}
