// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTenants = `-- name: CountTenants :one
SELECT COUNT(*) FROM tenants
`

func (q *Queries) CountTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    id,
    code,
    name,
    status,
    settings,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, code, name, status, settings, created_at, updated_at
`

type CreateTenantParams struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Status,
		arg.Settings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByCode = `-- name: GetTenantByCode :one
SELECT id, code, name, status, settings, created_at, updated_at FROM tenants
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetTenantByCode(ctx context.Context, code string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByCode, code)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, code, name, status, settings, created_at, updated_at FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, code, name, status, settings, created_at, updated_at FROM tenants
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Status,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET
    name = COALESCE($1, name),
    status = COALESCE($2, status),
    settings = COALESCE($3, settings),
    updated_at = NOW()
WHERE id = $4
RETURNING id, code, name, status, settings, created_at, updated_at
`

type UpdateTenantParams struct {
	Name     *string     `json:"name"`
	Status   *string     `json:"status"`
	Settings []byte      `json:"settings"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.Name,
		arg.Status,
		arg.Settings,
		arg.ID,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Status,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
